### ISSUE TITLE
THANK YOU!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [thyagoluciano/flutter_radio#1]
I've been waiting for someone to do this for months! Thanks. Testing. I heard this library was better.
![giphy](https://user-images.githubusercontent.com/23037821/44433482-4d29eb80-a55b-11e8-9062-b2861cb586e8.gif)

**Comment by ckildgypmk** [comment]
Your library really helped me a lot, thank you.

**Comment by thyagoluciano** [comment]
> Your library really helped me a lot, thank you.

I’m happy to help you
