### ISSUE TITLE
Not playing for all media/streaming types

### ISSUE THREAD

**Issue by suriyapr** [thyagoluciano/flutter_radio#40]
Only explicit MP3 files (local or remote) were playing, but not for all streaming types. For example, http://europa.shoutca.st:8106/stream2 (also we don't find any exception thrown).

**Comment by krunduev** [comment]
Plugin works with stream. Just tested.
You just need to allow http access from Android and iOS.
It by default have only https access.

iOS:
https://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

Android:
https://stackoverflow.com/questions/58407173/unable-connect-to-a-http-url-in-android-10

And also you need to add to Android manifest.
`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by suriyapr** [comment]
Thank you @krunduev 
Just enabled the below attribute in AndroidManifest.xml (..\android\app\src\main\AndroidManifest.xml) file and I am happy on listening.
 **android:usesCleartextTraffic="true"**

`<application
        android:name="io.flutter.app.FlutterApplication"
        android:usesCleartextTraffic="true"
...
</application>`
